version: '3.0'
services:
  rasa:
    build: .
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  action_server:
    image: rasa/rasa-sdk:3.3.0
    ports:
      - 5055:5055
    volumes:
      -  ./actions:/app/actions
